#!/bin/sh

# exports newest mixxx configs and music to given location
# must be called as the user with the mixxx configs in order to 
# get the proper .mixxx folder

# make sure there is a first arg
if [ -z $1 ]; then
	echo "usage: first arg is the target dir or machine"
	return -1
fi

# requires location to export to as first arg $1
USB=$1
echo "EXPORTING CONFIGS TO URI: "$USB

# find where script is located
DIR=$(cd $(dirname "$0"); pwd)

# find out where the music dir is located based on setting
MUSICDIR=$(head -n 1 $DIR/musicdir)

# update this installation's information
rsync -ri --progress --inplace --delete ~/.mixxx $DIR/../
rsync -ri --progress --inplace --delete $MUSICDIR/RealBest/added $DIR/../music/RealBest/

# make target's music dir in case it doesn't exist
mkdir -p $USB/quneo-mixxx/music/RealBest

# sync most recent stuff with given arg's quneo-mixxx directory
rsync --progress -riK $DIR/../.mixxx $USB/quneo-mixxx
rsync -riK --progress $DIR/../music/RealBest/added $USB/quneo-mixxx/music/RealBest

